spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/springboot-cp-java
    username: brinquedos_user
    password: 022501
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
      thymeleaf:
        cache: false
    server:
      port: 8080